// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: app/master-data/user/proto/user.proto

package user_proto

import (
	fmt "fmt"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "UserService.GetAllUser",
			Path:    []string{"/user"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
		{
			Name:    "UserService.GetOneUser",
			Path:    []string{"/user/{username}"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
	}
}

// Client API for UserService service

type UserService interface {
	GetAllUser(ctx context.Context, in *GetAllUserRequest, opts ...client.CallOption) (*GetAllUserResponse, error)
	GetOneUser(ctx context.Context, in *GetOneUserRequest, opts ...client.CallOption) (*GetOneUserResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) GetAllUser(ctx context.Context, in *GetAllUserRequest, opts ...client.CallOption) (*GetAllUserResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.GetAllUser", in)
	out := new(GetAllUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetOneUser(ctx context.Context, in *GetOneUserRequest, opts ...client.CallOption) (*GetOneUserResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.GetOneUser", in)
	out := new(GetOneUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	GetAllUser(context.Context, *GetAllUserRequest, *GetAllUserResponse) error
	GetOneUser(context.Context, *GetOneUserRequest, *GetOneUserResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		GetAllUser(ctx context.Context, in *GetAllUserRequest, out *GetAllUserResponse) error
		GetOneUser(ctx context.Context, in *GetOneUserRequest, out *GetOneUserResponse) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "UserService.GetAllUser",
		Path:    []string{"/user"},
		Method:  []string{"GET"},
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "UserService.GetOneUser",
		Path:    []string{"/user/{username}"},
		Method:  []string{"GET"},
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) GetAllUser(ctx context.Context, in *GetAllUserRequest, out *GetAllUserResponse) error {
	return h.UserServiceHandler.GetAllUser(ctx, in, out)
}

func (h *userServiceHandler) GetOneUser(ctx context.Context, in *GetOneUserRequest, out *GetOneUserResponse) error {
	return h.UserServiceHandler.GetOneUser(ctx, in, out)
}
