// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package user_sql

import (
	"database/sql"
	"time"
)

type MasterUser struct {
	ID           int64          `json:"ID"`
	Username     string         `json:"Username"`
	Password     string         `json:"Password"`
	Fullname     sql.NullString `json:"Fullname"`
	IsActive     bool           `json:"IsActive"`
	CreatedBy    int64          `json:"CreatedBy"`
	CreatedDate  time.Time      `json:"CreatedDate"`
	ModifiedDate time.Time      `json:"ModifiedDate"`
	ModifiedBy   int64          `json:"ModifiedBy"`
}
